export const ads = [
  {
    // img: "../public/products/cap.png",
    location: "г. Ташкент",
    descraption: "Кепки Corneliani Diamond for him edition.",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "2 599 000",
  },
  {
    img: "../public/products/car.png",
    location: "г. Самарканд",
    descraption: "Chevrolet Onix 1.2 Turbo в наличии",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "204 000 000",
  },
  {
    img: "../public/products/single_cap.png",
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
  },
  {
    img: "../public/products/sneakers.png",
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max Plus",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
  },
  {
    img: "../public/products/sneakers2.png",
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max 97",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
  },
  {
    img: "../public/products/watches.png",
    location: "г. Ташкент",
    descraption: "Apple Watch Series 8 - USA Non active",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 500 000",
  },
  {
    img: "../public/products/car2.png",
    location: "г. Самарканд",
    descraption: "Лучший кроссовер Geely Monjaro Limited Edition",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "320 000 000",
  },
  {
    img: "../public/products/makeUp.png",
    location: "г. Ташкент",
    descraption: "Стайлер для волос Dyson airwrap complete long",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "6 430 625",
  },
  {
    img: "../public/products/cap.png",
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
  },
  {
    img: "../public/products/car.png",
    location: "г. Самарканд",
    descraption: "Chevrolet Onix 1.2 Turbo в наличии",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "204 000 000",
  },
  {
    img: "../public/products/sneakers.png",
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max Plus",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
  },
  {
    img: "../public/products/single_cap.png",
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
  },
];

export const category = [
  {
    title: "Для женщин",
    dates: [],
    icon: "icon-girl",
    product_count: "4 147 объявлений",
  },
  {
    title: "Для мужчин",
    dates: [],
    icon: "icon-man",
    product_count: "4 147 объявлений",
  },
  {
    title: "Детские товары",
    dates: [],
    icon: "icon-walk",
    product_count: "4 147 объявлений",
  },
  {
    title: "Здоровье",
    dates: [],
    icon: "icon-heath",
    product_count: "4 147 объявлений",
  },
  {
    title: "Автотовары",
    dates: [],
    icon: "icon-fixed",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Канцелярия",
    dates: [],
    icon: "icon-pen",
    product_count: "4 147 объявлений",
  },
  {
    title: "Строительство и ремонт",
    dates: [],
    icon: "icon-builder",
    product_count: "4 147 объявлений",
  },
  {
    title: "Сумки и чемоданы",
    dates: [],
    icon: "icon-bag",
    product_count: "4 147 объявлений",
  },
  {
    title: "Дача, сады и огороды",
    dates: [],
    icon: "icon-plant",
    product_count: "4 147 объявлений",
  },
  {
    title: "Аксессуарлар",
    dates: [],
    icon: "icon-assessor",
    product_count: "4 147 объявлений",
  },
  {
    title: "Для женщин",
    dates: [],
    icon: "icon-girl",
    product_count: "4 147 объявлений",
  },
  {
    title: "Канцелярия",
    dates: [],
    icon: "icon-pen",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Аксессуарлар",
    dates: [],
    icon: "icon-assessor",
    product_count: "4 147 объявлений",
  },
  {
    title: "Сумки и чемоданы",
    dates: [],
    icon: "icon-bag",
    product_count: "4 147 объявлений",
  },
];

export const firstModal = [
  {
    title: "Добро пожаловать!",
    text: "Войти в систему чтобы торговать в системе",
    loginLable: "Логин",
    passLable: "Пароль",
    parol: "Забыли пароль?",
    login: "Войти",
    want: "Хотите стать продавцом?",
    sumbit: "Подать заявку"
  }
]
